services:
    spring_backend:
        image: "${DOCKER_REGISTRY}/${BACKEND_IMAGE_NAME}:${BACKEND_VERSION}"
        env_file: 
            - .env.base
            - ${PROFILE_ENV_FILE_PATH_REL}
        build:
            context: ./backend
        environment:
            - DATABASE_URL=${DATABASE_URL} # specified one more time, because changes when working outside of container. Such way takes precedence
            - APP_NAME_ENV=${BACKEND_BUILD_NAME}
            - ACTIVE_PROFILE_ENV=${ACTIVE_PROFILE}
        ports:
            - "8081:8080"
    postgres_prod_db:
        image: postgres:16.4-alpine3.20
        environment:
           - POSTGRES_USER=${DATABASE_USERNAME}
           - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
           - POSTGRES_DB=words_app_db
        ports: 
            - "5433:5432"
        volumes:
            - prod_db_volume:/var/lib/postgresql/data
    postgres_local_db:
        image: postgres:16.4-alpine3.20
        restart: no
        environment:
            - POSTGRES_USER=${DATABASE_USERNAME}
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_DB=words_app_db
        ports:
            - "5434:5432"
        volumes:
            - local_db_volume:/var/lib/postgresql/data

volumes:
    prod_db_volume:
    local_db_volume: