services:
    spring_backend:
        image: $DOCKER_REGISTRY/$BACKEND_IMAGE_NAME
        env_file:
            - .env
        depends_on:
            - postgresdb
        build: 
            context: ./backend
            args:
                - APP_NAME=$BACKEND_BUILD_NAME
                - APP_VERSION=$BACKEND_VERSION
        ports:
            - 8081:8080
    postgresdb:
        env_file:
            - .env
        image: postgres:16.4-alpine
        environment:
            - POSTGRES_USER=$POSTGRES_DOCKER_USERNAME
            - POSTGRES_PASSWORD=$POSTGRES_DOCKER_PASSWORD
            - POSTGRES_DB=$POSTGRES_DB
        ports: 
            - $POSTGRES_LOCAL_PORT:$POSTGRES_DOCKER_PORT
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
