services:
    spring_backend:
        image: $DOCKER_REGISTRY/$SPRING_IMAGE_NAME
        env_file:
            - .env
        depends_on:
            - $POSTGRES_SERVICE_NAME
        build: 
            context: ./backend
            args:
                - APP_NAME=$APP_BUILD_NAME
                - APP_VERSION=$APP_VERSION
        ports:
            - $SPRING_HOST_PROD_PORT:$SPRING_DOCKER_PROD_PORT
    postgresdb:
        env_file:
            - .env
        image: postgres:16.4-alpine
        environment:
            - POSTGRES_USER=$POSTGRES_ROOT_PROD_USERNAME
            - POSTGRES_PASSWORD=$POSTGRES_ROOT_PROD_PASSWORD
            - POSTGRES_DB=$POSTGRES_DEFAULT_DB
        ports: 
            - $POSTGRES_HOST_PROD_PORT:$POSTGRES_DOCKER_PROD_PORT
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
