api:
    root_path:
        api
    endpoints:
        words:
            root_path: words
            sprouts:
                read: read
                create: create
                update: update
                delete: delete
        users:
            root_path: users
            sprouts:
                info: info
                login: login
