api:
  root:
    name: api
    children:
      people:
        name: people
        endpoints:
          get_by_id:
      authentication:
        name: authentication
        endpoints:
          registration: registration
          login: login
          refresh_token: refresh_token
      word_languages:
        name: word-languages
        endpoints:
          get_all:
      words:
        name: words
        endpoints:
          get_all:
          update_one:
          create_one:
          get_by_id: