spring:
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always
  flyway:
    enabled: true
    locations: classpath:db/migration
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none