create table person (
    id bigint generated by default as identity primary key,
    username varchar unique not null,
    password varchar not null
);

create table languages (
    id bigint generated by default as identity primary key,
    title varchar unique not null
);

create table person_words (
    id bigint generated by default as identity primary key,
    title varchar unique not null,
    word_translation varchar not null,
    person_id bigint references person(id) not null,
    language_id bigint references languages(id) not null,
    local_date_time timestamp without time zone default current_timestamp not null
);
