create table language (
    id bigint generated by default as identity primary key,
    title varchar unique not null
);

create table word (
    id bigint generated by default as identity primary key,
    title varchar unique not null,
    translation varchar not null,
    description varchar not null,
    language_id bigint references language(id) not null,
    local_date_time timestamp without time zone default current_timestamp not null
);