create table account (
    id bigint generated by default as identity primary key,
    username varchar unique not null,
    password varchar not null,
    role varchar not null default 'USER'
);

create table language (
    id bigint generated by default as identity primary key,
    title varchar unique not null
);

create table word (
    id bigint generated by default as identity primary key,
    title varchar unique not null,
    translation varchar not null,
    description varchar not null,
    account_id bigint references account(id) not null,
    language_id bigint references language(id) not null,
    local_date_time timestamp without time zone default current_timestamp not null
);

create table token (
    id bigint generated by default as identity primary key,
    access varchar not null,
    refresh varchar not null,
    is_active boolean not null default false,
    account_id bigint references account(id) not null
);