create table word_groups (
    id bigint generated by default as identity primary key,
    title varchar not null unique,
    description varchar,
    created timestamp without time zone default current_timestamp not null,
    words_ids bigint[]
);