logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      springframework:
        security: DEBUG
    root: ERROR
    edu.architect_711.words.startup: INFO

server:
  port: 8083
  error:
    whitelabel:
      enabled: false