logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: TRACE
      springframework:
        security: DEBUG
    root: ERROR
    edu.architect_711.words.startup: INFO

server:
  port: ${SPRING_BACKEND_PORT}
  error:
    whitelabel:
      enabled: false

# Custom variables
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}