logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    root: ERROR

server:
  port: ${BACKEND_LOCAL_PORT}
  error.whitelabel.enabled: false

spring:
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true
  datasource:
    url: ${BACKEND_DATASOURCE_LOCAL_URL}
    username: ${POSTGRES_LOCAL_USERNAME}
    password: ${POSTGRES_LOCAL_PASSWORD}