spring:
  jackson.deserialization.fail-on-unknown-properties: true
  profiles:
    default: dev
    active: dev
  main:
    banner-mode: off
  config:
    import: classpath:config/database.yml,config/error.yml