spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${BACKEND_DATASOURCE_LOCAL_URL}
    username: ${POSTGRES_LOCAL_USERNAME}
    password: ${POSTGRES_LOCAL_PASSWORD}
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties.hibernate.format_sql: true
    show-sql: true