logging:
    level:
        org:
            springframework:
                security: DEBUG
        root: ERROR
        edu.architect_711.words.startup: INFO

# Variables from .env file. For Docker only
spring:
    datasource:
        url: ${SPRING_DATASOURCE_PROD_URL}
        username: ${POSTGRES_ROOT_PROD_USERNAME}
        password: ${POSTGRES_ROOT_PROD_PASSWORD}