spring:
    profiles:
        default: dev
        active: dev
    main:
        banner-mode: off
    config:
        import:
            classpath:/config/security.yaml, 
            classpath:/config/database.yml,
            classpath:/config/api.yml