logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    root: ERROR

server:
  port: ${SPRING_DEV_PORT}
  error.whitelabel.enabled: false

spring:
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_DEV_URL}
    username: ${POSTGRES_ROOT_DEV_USERNAME}
    password: ${POSTGRES_ROOT_DEV_PASSWORD}