spring:
  jackson.deserialization.fail-on-unknown-properties: true
  config:
    import: classpath:config/error.yaml
  profiles:
    default: "dev,postgres"

springdoc:
  api-docs:
    path: /api/documentation/docs
  swagger-ui:
    path: /api/documentation/swagger-ui.html

security:
  jwt:
    secret_key: ${JWT_SECRET_KEY}
    access_token_expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
    refresh_token_expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}