spring:
  main:
    banner-mode: off
  jpa:
    properties.hibernate.format_sql: true
    show-sql: true

logging:
  level:
    org:
      springframework.security: TRACE
      hibernate.orm.jdbc.bind: TRACE
    root: ERROR
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  error.whitelabel.enabled: false