logging:
  level:
    root: ERROR

server:
  port: ${BACKEND_LOCAL_PORT:8080}

spring:
  datasource:
    url: ${BACKEND_DATASOURCE_PROD_URL}
    username: ${POSTGRES_PROD_USERNAME}
    password: ${POSTGRES_PROD_PASSWORD}